"""empty message

Revision ID: 977bfa21e075
Revises: 29b684bbcc6d
Create Date: 2026-02-08 16:50:35.396495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977bfa21e075'
down_revision = '29b684bbcc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('media_post_id_fkey', 'user', ['post_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_post_id_fkey', 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###
